# Generated by Django 6.0.2 on 2026-03-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userprofile_role_userprofile_is_curator'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
